import React, { useCallback, useEffect, useMemo, useState } from "react";
import api from "../api/client";
import { useAuth } from "../context/AuthContext";

const statuses = ["Order Received", "Preparing", "Out for Delivery", "Delivered"];
const empty = { name: "", category: "base", price: "", stock: "", unit: "units", lowStockThreshold: "20" };

export default function Admin() {
  const { user } = useAuth(); const [items,setItems]=useState([]); const [orders,setOrders]=useState([]); const [analytics,setAnalytics]=useState(null); const [form,setForm]=useState(empty); const [editing,setEditing]=useState(null); const [tab,setTab]=useState("overview"); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const load = useCallback(async (silent=false) => { try { if(!silent)setBusy(true); const [i,o,a]=await Promise.all([api.get("/inventory"),api.get("/orders"),api.get("/orders/analytics")]); setItems(i.data);setOrders(o.data);setAnalytics(a.data);setError(""); } catch(e){setError(e.response?.data?.message||"Unable to load admin data.");} finally{if(!silent)setBusy(false);} },[]);
  useEffect(()=>{load(); const t=setInterval(()=>load(true),5000); return()=>clearInterval(t);},[load]);
  const lowCount=useMemo(()=>items.filter(i=>i.stock<=i.lowStockThreshold).length,[items]);
  const submit=async e=>{e.preventDefault();try{setBusy(true);setMessage("");const payload={...form,price:Number(form.price),stock:Number(form.stock),lowStockThreshold:Number(form.lowStockThreshold)};if(editing) await api.put(`/inventory/${editing}`,payload);else await api.post("/inventory",payload);setForm(empty);setEditing(null);setMessage(editing?"Inventory updated.":"Inventory item added.");await load(true);}catch(e){setError(e.response?.data?.message||"Unable to save inventory item.");}finally{setBusy(false);}};
  const remove=async id=>{if(!confirm("Delete this inventory item?"))return;try{await api.delete(`/inventory/${id}`);setMessage("Inventory item deleted.");await load(true);}catch(e){setError(e.response?.data?.message||"Unable to delete item.");}};
  const edit=item=>{setEditing(item._id);setForm({name:item.name,category:item.category,price:item.price,stock:item.stock,unit:item.unit,lowStockThreshold:item.lowStockThreshold});setTab("inventory");window.scrollTo({top:0,behavior:"smooth"});};
  const changeStatus=async(id,status)=>{try{await api.patch(`/orders/${id}/status`,{status});setOrders(prev=>prev.map(o=>o._id===id?{...o,status}:o));setMessage("Order status updated.");}catch(e){setError(e.response?.data?.message||"Unable to update status.");}};
  if(user?.role!=="admin") return <main className="page-shell"><div className="empty-state"><h2>Access denied</h2><p>Admin access is required.</p></div></main>;
  return <main className="admin-shell"><div className="admin-hero"><div><span className="eyebrow">PIZZAFLOW • ADMIN</span><h1>Operations Dashboard</h1><p>Monitor orders, inventory and low-stock alerts from one place.</p></div><button className="outline-btn" onClick={()=>load()}>{busy?"Refreshing…":"↻ Refresh"}</button></div>
    {message&&<div className="success-message">✓ {message}</div>}{error&&<div className="error-message">{error}</div>}
    <div className="admin-tabs"><button className={tab==="overview"?"selected":""} onClick={()=>setTab("overview")}>Overview</button><button className={tab==="orders"?"selected":""} onClick={()=>setTab("orders")}>Orders <b>{orders.filter(o=>o.paymentStatus==="paid"&&o.status!=="Delivered").length}</b></button><button className={tab==="inventory"?"selected":""} onClick={()=>setTab("inventory")}>Inventory {lowCount>0&&<b>{lowCount}</b>}</button></div>
    {tab==="overview"&&<><section className="stats-grid">{[["Total Orders",analytics?.totalOrders||0,"📦"],["Paid Orders",analytics?.paidOrders||0,"✓"],["Revenue",`₹${Number(analytics?.totalRevenue||0).toLocaleString("en-IN")}`,"₹"],["Low Stock",lowCount,"⚠️"]].map(([label,value,icon])=><div className="stat-card" key={label}><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div>)}</section><section className="admin-panel"><div className="panel-head"><div><h2>Recent Orders</h2><p>Live order operations. Updates every 5 seconds.</p></div><button className="text-btn" onClick={()=>setTab("orders")}>Manage all →</button></div><div className="admin-order-list">{orders.slice(0,5).map(o=><OrderRow key={o._id} order={o} onStatus={changeStatus}/>)}</div></section></>}
    {tab==="orders"&&<section className="admin-panel"><div className="panel-head"><div><h2>Order Management</h2><p>Change status and the customer dashboard updates automatically.</p></div></div><div className="admin-order-list">{orders.length?orders.map(o=><OrderRow key={o._id} order={o} onStatus={changeStatus}/>):<div className="empty-state">No orders yet.</div>}</div></section>}
    {tab==="inventory"&&<><section className="admin-panel"><div className="panel-head"><div><h2>{editing?"Edit Inventory Item":"Add Inventory Item"}</h2><p>Set stock and a custom threshold for automated alerts.</p></div></div><form className="inventory-form-new" onSubmit={submit}>{[["name","Item name","text"],["price","Price ₹","number"],["stock","Stock","number"],["unit","Unit","text"],["lowStockThreshold","Alert threshold","number"]].map(([name,ph,type])=><input key={name} name={name} type={type} min={type==="number"?0:undefined} placeholder={ph} value={form[name]} onChange={e=>setForm({...form,[name]:e.target.value})} required={name!=="unit"}/>)}<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="base">Base</option><option value="sauce">Sauce</option><option value="cheese">Cheese</option><option value="vegetable">Vegetable</option></select><button type="submit">{editing?"Save Changes":"Add Item"}</button>{editing&&<button type="button" className="outline-btn" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</button>}</form></section><section className="admin-panel"><div className="panel-head"><div><h2>Inventory</h2><p>{items.length} ingredients configured • {lowCount} below threshold</p></div></div><div className="inventory-table">{items.map(i=><div className={`inventory-row ${i.stock<=i.lowStockThreshold?"low-row":""}`} key={i._id}><div><strong>{i.name}</strong><small>{i.category} • ₹{i.price}</small></div><div><span className="stock-number">{i.stock}</span><small>{i.unit}</small></div><div><small>Alert at</small><strong>{i.lowStockThreshold}</strong></div><span className={`stock-badge ${i.stock<=i.lowStockThreshold?"low":"ok"}`}>{i.stock<=i.lowStockThreshold?"Low stock":"Healthy"}</span><div className="row-actions"><button onClick={()=>edit(i)}>Edit</button><button onClick={()=>remove(i._id)}>Delete</button></div></div>)}</div></section></>}
  </main>;
}

function OrderRow({order,onStatus}){return <div className="admin-order-row"><div className="order-id"><strong>#{order._id.slice(-6).toUpperCase()}</strong><small>{order.user?.name||"Customer"} • {order.user?.email||""}</small></div><div className="order-pizza"><strong>{order.pizza?.base} • {order.pizza?.sauce}</strong><small>{order.pizza?.cheese} {order.pizza?.vegetables?.length?`• ${order.pizza.vegetables.join(", ")}`:""}</small></div><div><strong>₹{Number(order.total).toLocaleString("en-IN")}</strong><small>{order.paymentStatus}</small></div><select value={order.status} disabled={order.paymentStatus!=="paid"} onChange={e=>onStatus(order._id,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></div>}
